-- PRESERVED GENERATION — SUPABASE DATABASE SETUP
-- Run this whole file once in Supabase Dashboard > SQL Editor.
-- After creating your admin account in Authentication > Users, run the
-- admin_users INSERT shown at the bottom with your user's UUID.

create extension if not exists pgcrypto;

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  date date not null,
  time text not null,
  location text not null,
  purpose text not null,
  dress text not null,
  price numeric(12,2) not null default 0 check (price >= 0),
  capacity integer not null default 100 check (capacity > 0),
  status text not null default 'active' check (status in ('active','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  source text,
  event_id uuid not null references public.events(id) on delete restrict,
  amount numeric(12,2) not null default 0,
  payment_method text not null default 'bank_transfer' check (payment_method in ('bank_transfer','payoneer')),
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','verified','cancelled')),
  ticket_code text not null unique,
  ticket_lookup_token uuid not null unique default gen_random_uuid(),
  ticket_status text not null default 'valid' check (ticket_status in ('valid','used','cancelled')),
  checked_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  type text not null default 'image' check (type in ('image','video')),
  media_url text not null,
  storage_path text,
  title text not null,
  description text,
  memory_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists registrations_event_id_idx on public.registrations(event_id);
create index if not exists registrations_ticket_code_idx on public.registrations(ticket_code);
create index if not exists registrations_created_at_idx on public.registrations(created_at desc);
create index if not exists gallery_memory_date_idx on public.gallery(memory_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists events_updated_at on public.events;
create trigger events_updated_at before update on public.events
for each row execute function public.set_updated_at();

drop trigger if exists registrations_updated_at on public.registrations;
create trigger registrations_updated_at before update on public.registrations
for each row execute function public.set_updated_at();

drop trigger if exists gallery_updated_at on public.gallery;
create trigger gallery_updated_at before update on public.gallery
for each row execute function public.set_updated_at();

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

grant execute on function public.is_current_user_admin() to anon, authenticated;

-- Public event-registration counts. It never exposes people's details.
create or replace view public.event_registration_counts
as
select
  e.id as event_id,
  count(r.id)::integer as registered
from public.events e
left join public.registrations r
  on r.event_id = e.id and r.payment_status <> 'cancelled'
group by e.id;

grant select on public.event_registration_counts to anon, authenticated;

-- Admin-only view. RLS on registrations still protects the underlying table.
create or replace view public.registrations_admin_view
with (security_invoker = true)
as
select
  r.id,
  r.first_name,
  r.last_name,
  r.email,
  r.phone,
  r.source,
  r.event_id,
  e.name as event_name,
  r.amount,
  r.payment_method,
  r.payment_status,
  r.ticket_code,
  r.ticket_status,
  r.checked_in_at,
  r.created_at
from public.registrations r
join public.events e on e.id = r.event_id;

grant select on public.registrations_admin_view to authenticated;

-- Atomically create a registration and ticket.
create or replace function public.register_for_event(
  p_first_name text,
  p_last_name text,
  p_email text,
  p_phone text,
  p_source text,
  p_event_id uuid
)
returns table (
  id bigint,
  ticket_code text,
  ticket_lookup_token uuid,
  payment_status text,
  amount numeric,
  event_name text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  e public.events%rowtype;
  current_count integer;
  code text;
  new_id bigint;
  new_token uuid;
  status_value text;
begin
  if length(trim(coalesce(p_first_name,''))) < 1
     or length(trim(coalesce(p_last_name,''))) < 1
     or length(trim(coalesce(p_email,''))) < 3
     or length(trim(coalesce(p_phone,''))) < 5 then
    raise exception 'Please complete all required fields.';
  end if;

  select * into e
  from public.events
  where id = p_event_id and status = 'active'
  for update;

  if not found then
    raise exception 'Event not found or no longer active.';
  end if;

  select count(*)::integer into current_count
  from public.registrations
  where event_id = e.id and payment_status <> 'cancelled';

  if current_count >= e.capacity then
    raise exception 'This event is now full.';
  end if;

  code := 'PG-' || to_char(current_date, 'YYYY') || '-' ||
          upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
  new_token := gen_random_uuid();
  status_value := case when e.price = 0 then 'paid' else 'pending' end;

  insert into public.registrations(
    first_name,last_name,email,phone,source,event_id,amount,
    payment_method,payment_status,ticket_code,ticket_lookup_token,ticket_status
  )
  values(
    trim(p_first_name),trim(p_last_name),lower(trim(p_email)),trim(p_phone),
    nullif(trim(coalesce(p_source,'')),''),e.id,e.price,'bank_transfer',
    status_value,code,new_token,'valid'
  )
  returning registrations.id into new_id;

  return query select new_id,code,new_token,status_value,e.price,e.name;
end;
$$;

grant execute on function public.register_for_event(text,text,text,text,text,uuid) to anon, authenticated;

-- Public ticket retrieval uses an unguessable token, not the numeric database ID.
create or replace function public.get_ticket_by_token(p_token uuid)
returns table (
  id bigint,
  first_name text,
  last_name text,
  email text,
  event_name text,
  event_date date,
  event_time text,
  location text,
  dress text,
  amount numeric,
  payment_status text,
  ticket_code text,
  ticket_status text,
  checked_in_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select r.id,r.first_name,r.last_name,r.email,e.name,e.date,e.time,e.location,e.dress,
         r.amount,r.payment_status,r.ticket_code,r.ticket_status,r.checked_in_at
  from public.registrations r
  join public.events e on e.id=r.event_id
  where r.ticket_lookup_token = p_token;
$$;

grant execute on function public.get_ticket_by_token(uuid) to anon, authenticated;

-- Verify bank transfer. Only an admin can do this.
create or replace function public.verify_registration_payment(p_registration_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_current_user_admin() then
    raise exception 'Admin access required.';
  end if;

  update public.registrations
  set payment_status='verified',
      ticket_status=case when ticket_status='cancelled' then ticket_status else 'valid' end
  where id=p_registration_id
    and payment_status <> 'cancelled';

  if not found then
    raise exception 'Registration not found or already cancelled.';
  end if;
  return true;
end;
$$;

grant execute on function public.verify_registration_payment(bigint) to authenticated;

-- Atomic, single-use event-day scan.
create or replace function public.scan_ticket(p_ticket_code text)
returns table (
  id bigint,
  first_name text,
  last_name text,
  event_name text,
  ticket_code text,
  ticket_status text,
  checked_in_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.registrations%rowtype;
  stamp timestamptz := now();
begin
  if not public.is_current_user_admin() then
    raise exception 'Admin access required.';
  end if;

  select * into r
  from public.registrations
  where ticket_code=upper(trim(p_ticket_code))
  for update;

  if not found then
    raise exception 'Ticket not found.';
  end if;

  if r.payment_status not in ('paid','verified') then
    raise exception 'Payment has not been verified yet.';
  end if;

  if r.ticket_status='cancelled' then
    raise exception 'This ticket has been cancelled.';
  end if;

  if r.ticket_status='used' then
    raise exception 'Ticket already used on %.', to_char(r.checked_in_at at time zone 'Africa/Lagos','DD Mon YYYY, HH12:MI AM');
  end if;

  update public.registrations
  set ticket_status='used', checked_in_at=stamp
  where id=r.id and ticket_status='valid';

  return query
  select r.id,r.first_name,r.last_name,e.name,r.ticket_code,'used'::text,stamp
  from public.events e where e.id=r.event_id;
end;
$$;

grant execute on function public.scan_ticket(text) to authenticated;

-- RLS
alter table public.events enable row level security;
alter table public.registrations enable row level security;
alter table public.gallery enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Public can view active events" on public.events;
create policy "Public can view active events" on public.events
for select to anon, authenticated
using (status='active');

drop policy if exists "Admins can manage events" on public.events;
create policy "Admins can manage events" on public.events
for all to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

drop policy if exists "Admins can view registrations" on public.registrations;
create policy "Admins can view registrations" on public.registrations
for select to authenticated
using (public.is_current_user_admin());

drop policy if exists "Admins can update registrations" on public.registrations;
create policy "Admins can update registrations" on public.registrations
for update to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

drop policy if exists "Public cannot read registrations directly" on public.registrations;
-- No anonymous SELECT policy. Registration creation happens only through the RPC.

drop policy if exists "Public can view gallery" on public.gallery;
create policy "Public can view gallery" on public.gallery
for select to anon, authenticated
using (true);

drop policy if exists "Admins can manage gallery" on public.gallery;
create policy "Admins can manage gallery" on public.gallery
for all to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

drop policy if exists "Admins can view admin users" on public.admin_users;
create policy "Admins can view admin users" on public.admin_users
for select to authenticated
using (public.is_current_user_admin());

-- Storage bucket for Gallery. Public read, admin-only write.
insert into storage.buckets (id,name,public)
values ('gallery','gallery',true)
on conflict (id) do update set public=true;

drop policy if exists "Gallery is publicly readable" on storage.objects;
create policy "Gallery is publicly readable" on storage.objects
for select to public
using (bucket_id='gallery');

drop policy if exists "Admins can upload gallery media" on storage.objects;
create policy "Admins can upload gallery media" on storage.objects
for insert to authenticated
with check (bucket_id='gallery' and public.is_current_user_admin());

drop policy if exists "Admins can update gallery media" on storage.objects;
create policy "Admins can update gallery media" on storage.objects
for update to authenticated
using (bucket_id='gallery' and public.is_current_user_admin())
with check (bucket_id='gallery' and public.is_current_user_admin());

drop policy if exists "Admins can delete gallery media" on storage.objects;
create policy "Admins can delete gallery media" on storage.objects
for delete to authenticated
using (bucket_id='gallery' and public.is_current_user_admin());

-- IMPORTANT:
-- After creating your admin user under Authentication > Users, copy that user's UUID
-- and run:
-- insert into public.admin_users(user_id) values ('PASTE-YOUR-AUTH-USER-UUID-HERE')
-- on conflict do nothing;
